definitions:
  caches:
    sonar: /opt/sonar-scanner/.sonar
  services:
    docker-build:
       memory: 10240
       type: docker
clone:
  depth: full

pipelines: 
  custom: 
    manual_sonarqube:
      -
        step: 
          name: SonarQube analysis
          image: sonarsource/sonar-scanner-cli:latest
          size: 4x
          runtime:
            cloud:
              atlassian-ip-ranges: true
          caches:
            - sonar
          script:
            - |
              sonar-scanner \
              -Dsonar.projectKey=${BITBUCKET_REPO_SLUG} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.token=${SONAR_TOKEN}
      -
        step:
          name: CycloneDX
          image: python:3.13.4-slim-bullseye
          size: 4x
          runtime:
            cloud:
              atlassian-ip-ranges: true
          script:
            - export PIP_ROOT_USER_ACTION=ignore
            - python -m pip install cyclonedx-bom
            - |
              cyclonedx-py \
              requirements \
              --mc-type application \
              -o sbom.json \
              requirements.txt
            - apt-get update -y
            - apt-get install -y curl nano
            - |
              curl "${DT_API_BOM_URL}" \
              -w "\n" \
              -H "Content-Type: multipart/form-data; boundary=__X_BOM__" \
              -H "X-Api-Key: ${DT_APIKEY}" \
              -F "autoCreate=true" \
              -F "projectName=${BITBUCKET_REPO_SLUG}" \
              -F "projectVersion=${BITBUCKET_BRANCH}" \
              -F "bom=@\"sbom.json\""
          artifacts:
            - sbom.json